<?php
return array(
	//'配置项'=>'配置值'
	'TOKEN'=>'wangjingjun',
	'appid'=>'wxeb69dcc420d95b6b',//wxe917ffe5098a8e4f
	'secret'=>'212f044fcdd1a399b2c4209ecf42c6ab',//0b8e9effc192e686a2703804555ff4a0
	//公众号菜单配置,翻译控制器translate
           'MENU'     =>   '{
		           "button":[
			          	{
			          		"name":"公共查询",
			          		"sub_button":[
						{
							"type":"click",
							"name":"天气查询",
							"key":"广州"
						},
						{
							"type":"click",
							"name":"公交查询",
							"key":"公交"
						},
						{
							"type":"click",
							"name":"翻译查询",
							"key":"翻译"
						},
						{	"type":"view",
							"name":"转视频链接",
							"url":"http://www.ice20.top/weixin2/Wechat.php/product/homepage"
						}
			          		]
			          	},
			          	{
			          		"name":"山灵商城",
			          		"sub_button":[
						{
							"type":"view",
							"name":"商城首页",
							"url":"http://www.ice20.top/weixin2/Wechat.php/product/homepage"
						},
						{
							"type":"view",
							"name":"最新商品",
							"url":"http://www.ice20.top/weixin2/Wechat.php/product/new_product"
						},
						{
							"type":"view",
							"name":"优惠商品",
							"url":"http://www.ice20.top/weixin2/Wechat.php/product/discount_price"
						},
						{
							"type":"view",
							"name":"限时特价",
							"url":"http://www.ice20.top/weixin2/Wechat.php/product/limit_price"
						}
			          		]
			          	},
			          	{
			          		"name":"山灵会员",
			          		"sub_button":[
						{
							"type":"view",
							"name":"会员中心",
							"url":"http://www.ice20.top/weixin2/Wechat.php/user/membercenter"
						},
						{
							"type":"view",
							"name":"会员信息",
							"url":"http://www.ice20.top/weixin2/Wechat.php/index/get_userinfo"
						},
						{
							"type":"click",
							"name":"会员签到",
							"key":"签到"
						}
			          		]
			          	}
		           ]
		 }',

);