<?php
return array(
	//'配置项'=>'配置值'
	'TOKEN'=>'wangjingjun',
	'appid'=>'wxeb69dcc420d95b6b',//wxe917ffe5098a8e4f
	'secret'=>'212f044fcdd1a399b2c4209ecf42c6ab',//0b8e9effc192e686a2703804555ff4a0
	//公众号菜单配置,翻译控制器translate
           'MENU'     =>   '{
		           "button":[
			          	{
			          		"name":"公共查询",
			          		"sub_button":[
						{
							"type":"click",
							"name":"天气查询",
							"key":"weather"
						},
						{
							"type":"view",
							"name":"公交查询",
							"url":"http://map.baidu.com/mobile/webapp/index/index/"
						},
						{
							"type":"view",
							"name":"VIP视频转链",
							"url":"http://www.ice20.top/weixin2/Wechat.php/Api/translink"
						},
						{
							"type":"click",
							"name":"翻译查询",
							"key":"翻译"
						}
			          		]
			          	},
			          	{
			          		"name":"山灵商城",
			          		"sub_button":[
						{
							"type":"view",
							"name":"商城首页",
							"url":"http://www.ice20.top/weixin2/index/homepage"
						},
						{
							"type":"view",
							"name":"最新商品",
							"url":"http://www.ice20.top/weixin2/product/new_product"
						},
						{
							"type":"view",
							"name":"优惠商品",
							"url":"http://www.ice20.top/weixin2/product/discount_price"
						},
						{
							"type":"view",
							"name":"限时特价",
							"url":"http://www.ice20.top/weixin2/product/limit_price"
						}
			          		]
			          	},
			          	{
			          		"name":"山灵会员",
			          		"sub_button":[
						{
							"type":"view",
							"name":"会员中心",
							"url":"http://www.ice20.top/weixin2/user/membercenter"
						},
						{
							"type":"click",
							"name":"会员信息",
							"key":"userinfo"
						},
						{
							"type":"click",
							"name":"会员签到",
							"key":"sign"
						}
			          		]
			          	}
		           ]
		 }',

);